### PR TITLE
New version of the website

### PR DESCRIPTION
**Pull request by Gonzih**
# What was done:
* new theme
* new css from scratch
* responsive design
* re-captcha on feedback form
* support for separate pages
* contact, ,coc and location is now separate pages
* blog implementation (hidden for now, no content there, can be found at `/blog/`) url

Main page:

# Large:
image

# Medium:
image

# Small:
image

# Contact page:
image

# Location:
image

# CoC:
image

### CODE REVIEW

**Comment by mfridman** [comment]
Awesome job, it looks great!

For contact, location and code of conduct, is it a separate page? We probably shouldn't display the logo+gopher on separate pages in general. From the user's perspective it appears as if nothing happened following a click (i.e., they wouldn't know to scroll down)

nav

**Comment by mfridman** [comment]
Should we keep the fixed navbar, I find they provide a better UX to enable user's to hop around between sections to various pages.

**Comment by Gonzih** [comment]
Yes fixed navbar is how it works atm. I will think how to hide hero 
section conditionally on pages in hugo.

**Comment by Gonzih** [comment]
Now hero section is hidden on all pages except the index one

# Contact form:
image
image

# coc
image

# location

image

**Pull request merged**
